### ISSUE TITLE
error when try to generate content

### ISSUE THREAD

**Issue by hafriz** [developerck/moodle-atto_aic#1]
hi, after installing the plugin and put the openai key. try to generate content. error shown as below

{"error":"Exception - Class 'curl' not found","errorcode":"generalexceptionmessage","stacktrace":"* line 72 of \/lib\/editor\/atto\/plugins\/aic\/classes\/ai.php: Error thrown\n* line 38 of \/lib\/editor\/atto\/plugins\/aic\/ajax.php: call to atto_aic\\ai::generate_text()\n"

**Comment by developerck** [comment]
which version of moodle you are using ?

**Comment by hafriz** [comment]
I'm using moodle version 4.1

**Comment by developerck** [comment]
can you please try with latest release 1.1 and please update/

**Comment by hafriz** [comment]
hi @developerck 

here is the error 

{"error":"Error occurred","errorcode":"error","stacktrace":"* line 83 of \/lib\/editor\/atto\/plugins\/aic\/classes\/ai.php: moodle_exception thrown\n* line 38 of \/lib\/editor\/atto\/plugins\/aic\/ajax.php: call to atto_aic\\ai::generate_text()\n","debuginfo":"\nError code: error",

**Comment by hafriz** [comment]
hi @developerck 

i think this is might be the error : 

"message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",

**Comment by cyclonmaster** [comment]
I had same problem,

moodle-3.10.3
moodle-atto_aic-1.2
gpt-3.5-turbo-instruct

Error:
{"error":"Error occurred","errorcode":"error","stacktrace":null,"debuginfo":null,"reproductionlink":null}

Please advice.

**Comment by developerck** [comment]
please use latest package from github.

**Comment by cyclonmaster** [comment]
moodle-atto_aic-1.2 is not latest? I don't see any later than 1.2.

**Comment by developerck** [comment]
This is latest.

**Comment by cyclonmaster** [comment]
no wonder....my openai api free trials already expired. I wonder if this plugin will support google gemini in future?
