### ISSUE TITLE
atto aic 1.1 with moodle 4.1 not show button at atto toolbar (atto toolbar edit = aic)

### ISSUE THREAD

**Issue by cyclonmaster** [developerck/moodle-atto_aic#3]
Version:
Atto aic version 1.1
Moodle version 4.1

Atto toolbar settings/Toolbar config:
edit = aic

Allowed role:
Tick all

Problem with AIC content generator:
Not show button at atto toolbar. Suppose to appear at the left of expand button.

**Comment by developerck** [comment]
Thanks for posting.
This has been fixed. 
by default, including siteadmin does not have any role return by the function, however, the have virtual role as "authenticated user".
In short, if you can create a system level role and assign that to any user, then it could have worked.
Now, if authenticated user is selected, this will also work for all.
