### ISSUE TITLE
missing icon in toolbar

### ISSUE THREAD

**Issue by bhavel** [developerck/moodle-atto_aic#7]
Version 4.1
After installation i set the toolbar. The icon is missing in the editor.
Tnx Bohus

**Comment by Manu-REMY** [comment]
Hi,

Moodle 4.3.3+ : Still no icon after installation and set the toolbar.

Thanks.

**Comment by developerck** [comment]
the main issue was , admin was not allowed by default to use this plugin. so i have added one more option. and released a new verison. Thanks for reporting and this is fix now.

**Comment by bhavel** [comment]
great, it works!
Thanks

**Comment by Manu-REMY** [comment]
Thanks.
Works fine now.
